### ISSUE TITLE
Logic should return at least information about clicked cell 

### ISSUE THREAD

**Issue by dev-in-disguise** [Flash0ver/F0.Minesweeper#61]
*GIVEN* a user flags a cell 
*AND* the user clicks on another cell which would auto-uncover the flagged cell
*WHEN* the user now tries to uncover the previously flagged cell
*THEN* I expect the logic library to return the already uncovered cells in the report

With this fix I then could e.g. click cell x=5, y=5 from below image to uncover it. 
![image](https://user-images.githubusercontent.com/16714208/111668644-3ed90480-8816-11eb-9b88-763597428839.png)

**Comment by thomas-pemsel** [comment]
Niiiice, I just wanted to investigate further, and I see that this has already been fixed in commit [3f745f1](https://github.com/Flash0ver/F0.Minesweeper/pull/72/commits/3f745f172860d1cf1d85aa1bfb215f0aabe152d2) :D
You can see the fixed behaviour in the [Preview version](https://flash0ver.github.io/F0-Games-Minesweeper-Preview/game) of the game ;)
So, yeah, let's review this in the next session, but I think we can close this issue. 🎉🍻
